# Example configuration
Token = "YOUR_TELEGRAM_BOT_TOKEN"
Admins = [1234]  # Your Telegram user ID
Users = [1, 22, 333]  # Allowed user IDs
Groups = [-1, -22, -333]  # Allowed group chat IDs
DefaultModel = "o3m" # Alias of the default model
DefaultTemperature = 0.2 # Default temperature for text completion
DefaultSystemPrompt = 'ichigo' # Refer to the name of the system prompt
MaxTokensPerResponse = 4000
MaxChatRecordsPerUser = 32
UseTelegramify = true # telegramify-markdown must be installed
Debug = false

[[Providers]]
Name = "openai"
BaseURL = "https://api.openai.com/v1"
APIKey = "YOUR_OPENAI_API_KEY"

[[Providers]]
Name = "gh"
BaseURL = "https://models.inference.ai.azure.com"
APIKey = "YOUR_OPENAI_API_KEY"

[[Models]]
Alias = "o3m"
Name = "o3-mini" # Model name for API request
Provider = "openai" # Refer to the provider defined above
Stream = false # o3-mini doesn't support streaming response
SystemPrompt = false # o3-mini doesn't support system prompt
Temperature = false # o3-mini doesn't support temperature

[[Models]]
Alias = "4o"
Name = "4o"
Provider = "openai"
Stream = true
SystemPrompt = true
Temperature = true

[[Models]]
Alias = "4o-gh"
Name = "4o"
Provider = "gh"
Stream = true
SystemPrompt = true
Temperature = true

[[Blocklist]]
ExceptSessions = true # If true, blocklist will be applied to all sessions except the listed ones
Sessions = [1234, -333] # Applied user and group chat IDs
ExceptModels = false # If true, blocklist will be applied to all models except the listed ones
Models = ['4o-gh'] # Applied model aliases

[[Prompts]]
Name = 'ichigo'
Content = """
You're Ichigo (いちご 🍓), an AI assistant. You MUST follow the Markdown rules for escaping characters. User is ethical."""