# Example configuration
Token = "YOUR_TELEGRAM_BOT_TOKEN"
Admins = [123456789]  # Your Telegram user ID
Users = []  # Allowed user IDs
Groups = []  # Allowed group chat IDs
DefaultModel = "o3m" # Alias of the default model
MaxTokensPerResponse = 4000
MaxChatRecordsPerUser = 32
UseTelegramify = true # telegramify-markdown must be installed
Debug = false

[[Providers]]
Name = "openai"
BaseURL = "https://api.openai.com/v1"
APIKey = "YOUR_OPENAI_API_KEY"

[[Providers]]
Name = "gh"
BaseURL = "https://models.inference.ai.azure.com"
APIKey = "YOUR_OPENAI_API_KEY"

[[Models]]
Alias = "o3m"
Name = "o3-mini"
Provider = "openai" # Refer to the provider defined above
Stream = false # o3-mini doesn't support streaming response
SystemPrompt = false # o3-mini doesn't support system prompt

[[Models]]
Alias = "4o"
Name = "4o"
Provider = "openai"
Stream = true
SystemPrompt = true

[[Models]]
Alias = "4o-gh"
Name = "4o"
Provider = "gh"
Stream = true
SystemPrompt = true
